### ISSUE TITLE
paramiko is required but does not appear to be installed

### ISSUE THREAD

**Issue by squeeb** [Dell-Networking/ansible-dellos-examples#3]
Getting the error: 

```
ansible-playbook -i inventory.yaml getfacts_os9.yaml

PLAY [dellos9] *****************************************************************

TASK [Gather Dell EMC OS9 Device Facts] ****************************************
fatal: [hq-3f-sw1]: FAILED! => {"changed": false, "failed": true, "msg": "paramiko is required but does not appear to be installed.  It can be installed using  `pip install paramiko`"}
```

Paramiko is installed, this appears to be coming from the switch.

**Comment by skg-net** [comment]
Hi @squeeby,

This has nothing to do with the switch, since we os9 modules are executed on local connection mode.

>  connection=local 

We have seen this error, in some of our development environment. what we found out was the installation of ``paramiko`` was not successful in those cases.

Try this out in your Ansible control host and let us know.

``python -c 'import paramiko; from paramiko.ssh_exception import AuthenticationException;'``

Thanks,
Senthil Kumar G.
